config/routes.rb
Rails.application.routes.draw do
  

  resources :text_blocks
  resources :jobs
  resources :projects
  get 'pages/resume'
  get 'pages/intention'
  get 'pages/contact'
  get 'pages/about'
  get 'pages/now'
  get 'pages/product_portfolio'
  get 'pages/dev_portfolio'
  
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_rich_text :org_summary
  has_rich_text :summary
  has_rich_text :highlights
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :summary
  has_rich_text :organization_context
  has_rich_text :project_context
  has_rich_text :problem
  has_rich_text :solution_parameters
  has_rich_text :process
  has_rich_text :solution
end

app/models/text_block.rb
class TextBlock < ApplicationRecord
    has_rich_text :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.order(year: :desc, end_year: :asc)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to :jobs, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: :jobs }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:year, :title, :org, :org_summary, :summary, :highlights, :end_year, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @ten_secs = TextBlock.where(shortname: "me in 10 seconds")[0].body
  end

  def about
    @about = TextBlock.where(shortname: "about")[0].body
  end

  def now
  end

  def intention
    @intention = TextBlock.where(shortname: "intention")[0]
  end

  def product_portfolio
    @product_projects = Project.where(portfolio_group: "product")
  end

  def dev_portfolio
    @dev_projects = Project.where(portfolio_group: "dev")
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :portfolio_group, :role, :organization, :industry, :project_type, :skills, :technologies, :organization_context, :project_context, :problem, :solution_parameters, :process, :solution, :summary, :text)
    end
end

app/controllers/text_blocks_controller.rb
class TextBlocksController < ApplicationController
  before_action :set_text_block, only: [:show, :edit, :update, :destroy]

  # GET /text_blocks
  # GET /text_blocks.json
  def index
    @text_blocks = TextBlock.all
  end

  # GET /text_blocks/1
  # GET /text_blocks/1.json
  def show
  end

  # GET /text_blocks/new
  def new
    @text_block = TextBlock.new
  end

  # GET /text_blocks/1/edit
  def edit
  end

  # POST /text_blocks
  # POST /text_blocks.json
  def create
    @text_block = TextBlock.new(text_block_params)

    respond_to do |format|
      if @text_block.save
        format.html { redirect_to @text_block, notice: 'Text block was successfully created.' }
        format.json { render :show, status: :created, location: @text_block }
      else
        format.html { render :new }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_blocks/1
  # PATCH/PUT /text_blocks/1.json
  def update
    respond_to do |format|
      if @text_block.update(text_block_params)
        format.html { redirect_to @text_block, notice: 'Text block was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_block }
      else
        format.html { render :edit }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_blocks/1
  # DELETE /text_blocks/1.json
  def destroy
    @text_block.destroy
    respond_to do |format|
      format.html { redirect_to text_blocks_url, notice: 'Text block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_block
      @text_block = TextBlock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def text_block_params
      params.require(:text_block).permit(:shortname, :body, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/text_blocks_helper.rb
module TextBlocksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :end_year %>
    <%= form.number_field :end_year %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :org %>
    <%= form.text_field :org %>
  </div>

  <div class="field">
    <%= form.label :org_summary %>
    <%= form.rich_text_area :org_summary %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.rich_text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :highlights %>
    <%= form.rich_text_area :highlights %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>End Year</th>
      <th>Title</th>
      <th>Org</th>
      <th>Org summary</th>
      <th>Summary</th>
      <th>Highlights</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.year %></td>
        <td><%= job.end_year %></td>
        <td><%= link_to job.title, job %></td>
        <td><%= link_to job.org, job %></td>
        <td><%= job.org_summary %></td>
        <td><%= job.summary %></td>
        <td><%= job.highlights %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Years:</strong>
  <%= @job.year %>
  <% if @job.end_year? %>
   - <%= @job.end_year %>
   <% else %>
   <% end -%>
</p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Org:</strong>
  <%= @job.org %>
</p>

<p>
  <strong>Org summary:</strong>
  <%= @job.org_summary %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @job.summary %>
</p>

<p>
  <strong>Highlights:</strong>
  <%= @job.highlights %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>NickMakes</title>
    <%= favicon_link_tag asset_path 'made_by_nick_light_icon.png' %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text&family=Montserrat:wght@500&family=Rowdies:wght@700&display=swap" rel="stylesheet">
  
  </head>

  <body>
    <div class="mast-containter">
      <div class="big-mast">
        <%= link_to "Nick Smith", root_path, class: "header-link" %>
      </div>
      <div class="small-mast">
        <% if yield(:title).empty? %>
            
          <% else %>
            > <%= yield(:title) %>
          <% end %>
      </div>
    </div>

    <% if false %>

    <table class='mast'><tr>
      <td class="mast-big">
        <%= link_to "Nick Smith", root_path, class: "header-link" %>
      </td>
      <td class="mast-small">
          <% if yield(:title).empty? %>
            
          <% else %>
            > <%= yield(:title) %>
          <% end %>
      </td>
    </tr></table>
    
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>
<%= @about %>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/dev_portfolio.html.erb
<% provide(:title, "Software I've Developed") %>

<% @dev_projects.each{|proj| %>
	<p><%= proj.title %></p>
	<p><small>Summary</small></p> 
	<p><%= proj.summary %></p>
	<%= link_to "Learn more about the project here.", proj %>
	<hr>
<% } %>

app/views/pages/home.html.erb
<h2>Me in 10 seconds</h2>
<%= @ten_secs %>

<h2>Stuff I've Made</h2>
<p><%= link_to "Product management portfolio", pages_product_portfolio_path %></p>
<p><%= link_to "Software development portfolio", pages_dev_portfolio_path %></p> 
<p><%= link_to "Everywhere I've ever worked", pages_resume_path %></p> 

<h2>Me in 10 minutes?</h2>
<p>See my <%= link_to "about", pages_about_path%> page.</p>

<h2>Contact</h2>
<p><%= link_to "What I'm looking for right now", pages_intention_path %></p>
<p>Email me at <%= mail_to "digitaldoesnthurt@gmail.com", "digitaldoesnthurt@gmail.com" %></p>



<% if false %>




<h2>What am i doing now?</h2>
<p>See my "<%= link_to "now", pages_now_path %>" page.</p>


<p></p>
<% end -%>

app/views/pages/intention.html.erb
<% provide(:title, "What I'm looking for") %>

<%= @intention.body %>
<p></p>

app/views/pages/now.html.erb
<h1>Pages#now</h1>
<p>Find me in app/views/pages/now.html.erb</p>

app/views/pages/resume.html.erb
<% provide(:title, "Resume") %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form-table">
    <tr>
      <td>
        <div class="field">
          <%= form.label :project_title %>
          <%= form.text_field :title %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= form.label :portfolio_group %>
          <%= form.text_field :portfolio_group %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= form.label :role %>
          <%= form.text_field :role %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= form.label :organization %>
          <%= form.text_field :organization %>
        </div> 
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= form.label :industry %>
          <%= form.text_field :industry %>
        </div>       
      </td>
      <td>
        <div class="field">
          <%= form.label :project_type %>
          <%= form.text_field :project_type %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= form.label :skills %>
          <%= form.text_field :skills %>
        </div>  
      </td>
      <td>
        <div class="field">
          <%= form.label :technologies %>
          <%= form.text_field :technologies %>
        </div>      
      </td>
    </tr>
  </table>

  <div class="field">
    <%= form.label :summary %>
    <%= form.rich_text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :organization_context %>
    <%= form.rich_text_area :organization_context %>
  </div>

  <div class="field">
    <%= form.label :project_context %>
    <%= form.rich_text_area :project_context %>
  </div>

  <div class="field">
    <%= form.label :problem %>
    <%= form.rich_text_area :problem %>
  </div>

  <div class="field">
    <%= form.label :solution_parameters %>
    <%= form.rich_text_area :solution_parameters %>
  </div>

  <div class="field">
    <%= form.label :process %>
    <%= form.rich_text_area :process %>
  </div>

  <div class="field">
    <%= form.label :solution %>
    <%= form.rich_text_area :solution %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="admin-container">
<h2>Editing Project</h2>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>
<p id="notice"><%= notice %></p>

<table align="center">
  <tr>
    <td>
      <h2>Projects</h2>      
    </td>
    <td style="vertical-align: bottom;">
      <%= link_to 'New Project', new_project_path %>
    </td>
  </tr>
</table>



<div class="poster-board">
  <% @projects.in_groups_of(2).each do |project_group| %>

      <% project_group.each{ |proj| %>
        <% unless proj.nil? %>
          <div class="poster">
            <div class="poster-head">
              <%= link_to proj.title, proj %> <small>(<%= proj.portfolio_group %>)</small>
            </div>
            <div class="poster-body">
              <%= proj.summary %>
            </div>
          </div>
        <% end %>
      <% } %>  
    
  <% end %>  
</div>
  


<br><br><br>
<br><br><br>
<br><br><br>
<hr>
<br><br><br>
<br><br><br>
<br><br><br>

<h2>Projects</h2>
<%= link_to 'New Project', new_project_path %>
<table class="scaffold-index">
  <thead>
    <tr>
      <th>Title</th>
      <th>Portfolio group</th>
      <th>Role</th>
      <th>Organization</th>
      <th>Industry</th>
      <th>Project type</th>
      <th>Skills</th>
      <th>Technologies</th>
      <th>Summary</th>
      <th>Organization context</th>
      <th>Project context</th>
      <th>Problem</th>
      <th>Solution parameters</th>
      <th>Process</th>
      <th>Solution</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, project %></td>
        <td><%= project.portfolio_group %></td>
        <td><%= project.role %></td>
        <td><%= project.organization %></td>
        <td><%= project.industry %></td>
        <td><%= project.project_type %></td>
        <td><%= project.skills %></td>
        <td><%= project.technologies %></td>
        <td><%= project.summary %></td>
        <td><%= project.organization_context %></td>
        <td><%= project.project_context %></td>
        <td><%= project.problem %></td>
        <td><%= project.solution_parameters %></td>
        <td><%= project.process %></td>
        <td><%= project.solution %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<div class="admin-container">
	<h2>New Project</h2>

	<%= render 'form', project: @project %>

	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<h2><%= @project.title %></h2>

<table class="detail-table">
  <thead>
    <% unless @project.role.empty? %>
      <th scope="col">role</th>
    <% end -%>
    <% unless @project.organization.empty? %>
      <th scope="col">organization</th>
    <% end -%>
    <% unless @project.industry.empty? %>  
      <th scope="col">industry</th>
    <% end -%>
    <% unless @project.project_type.empty? %>
      <th scope="col">project type</th>
    <% end -%>
    <% unless @project.skills.empty? %>
      <th scope="col">skills</th>
    <% end -%>  
    <% unless @project.technologies.empty? %>
      <th scope="col">technologies</th>
    <% end -%>
  </thead>
  <tr>
    <% unless @project.role.empty? %>
      <td data-label="role">
        <%= @project.role %>
      </td>
    <% end -%>  
    <% unless @project.organization.empty? %>
      <td data-label="organization">
        <%= @project.organization %>
      </td>
    <% end -%>
    <% unless @project.industry.empty? %>  
      <td data-label="industry">
        <%= @project.industry %>
      </td>
    <% end -%>
    <% unless @project.project_type.empty? %>  
      <td data-label="project type">
        <%= @project.project_type %>
      </td>
    <% end -%>
    <% unless @project.skills.empty? %>
      <td data-label="skills">
        <%= @project.skills %>
      </td>
    <% end -%>
    <% unless @project.technologies.empty? %>
      <td data-label="technologies">
        <%= @project.technologies %>
      </td>
    <% end -%>
  </tr>
</table>



<% unless @project.summary.empty? %>
<p>
  <strong>Summary</strong>
  <%= @project.summary %>
</p>
<% end -%>

<% unless @project.organization_context.empty? %>
<p>
  <strong>Organization context:</strong>
  <%= @project.organization_context %>
</p>
<% end -%>

<% unless @project.project_context.empty? %>
<p>
  <strong>Project context:</strong>
  <%= @project.project_context %>
</p>
<% end -%>

<% unless @project.problem.empty? %>
<p>
  <strong>Problem:</strong>
  <%= @project.problem %>
</p>
<% end -%>

<% unless @project.solution_parameters.empty? %>
<p>
  <strong>Solution parameters:</strong>
  <%= @project.solution_parameters %>
</p>
<% end -%>

<% unless @project.process.empty? %>
<p>
  <strong>Process:</strong>
  <%= @project.process %>
</p>
<% end -%>

<% unless @project.solution.empty? %>
<p>
  <strong>Solution:</strong>
  <%= @project.solution %>
</p>
<% end %>

app/views/text_blocks/_form.html.erb
<%= form_with(model: text_block, local: true) do |form| %>
  <% if text_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text_block.errors.count, "error") %> prohibited this text_block from being saved:</h2>

      <ul>
        <% text_block.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shortname %>
    <%= form.text_field :shortname %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/text_blocks/edit.html.erb
<h1>Editing Text Block</h1>

<%= render 'form', text_block: @text_block %>

<%= link_to 'Show', @text_block %> |
<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Text Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Shortname</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_blocks.each do |text_block| %>
      <tr>
        <td><%= text_block.shortname %></td>
        <td><%= text_block.body %></td>
        <td><%= link_to 'Show', text_block %></td>
        <td><%= link_to 'Edit', edit_text_block_path(text_block) %></td>
        <td><%= link_to 'Destroy', text_block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text Block', new_text_block_path %>

app/views/text_blocks/new.html.erb
<h1>New Text Block</h1>

<%= render 'form', text_block: @text_block %>

<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shortname:</strong>
  <%= @text_block.shortname %>
</p>

<p>
  <strong>Body:</strong>
  <%= @text_block.body %>
</p>

<%= link_to 'Edit', edit_text_block_path(@text_block) %> |
<%= link_to 'Back', text_blocks_path %>